name: Auto-Grading

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  autograder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run Tests
        run: python tests/test_script.py

